export {default as Home} from './home/home'
export {default as Login} from './login/login'
export {default as Other} from './other/other'
export {default as Signin} from './signin/signin'
export {default as Success} from './success/success'
export {default as Tweets} from './tweets/tweets'
export {default as My} from './my/my'
export {default as New} from './new/new'